<a href="https://www.kaggle.com/code/tommasofacchin/02-resident-evil-dataset-demo-eda?scriptVersionId=305834233" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Resident Evil - Dataset demo & EDA

Demo & **EDA** for the dataset "Resident Evil" created by me in this notebook:
https://www.kaggle.com/code/tommasofacchin/01-resident-evil-data-scraping-and-generation

In [1]:
import pandas as pd

games = pd.read_csv("/kaggle/input/datasets/tommasofacchin/resident-evil/games.csv")
characters = pd.read_csv("/kaggle/input/datasets/tommasofacchin/resident-evil/characters.csv")
gameAppearance = pd.read_csv("/kaggle/input/datasets/tommasofacchin/resident-evil/gameAppearance.csv")
interactions = pd.read_csv("/kaggle/input/datasets/tommasofacchin/resident-evil/interactions.csv")
scenes = pd.read_csv("/kaggle/input/datasets/tommasofacchin/resident-evil/scenes.csv")

## Games

this table contains the main games and spinoffs, with title, year, type and chronology order.

In [2]:
games.head(15)

,id,title,year,type,chronology_order
0,re,Resident Evil,1996,mainline,2
1,re2,Resident Evil 2,1998,mainline,4
2,re3,Resident Evil 3: Nemesis,1999,mainline,3
3,re_ve,Resident Evil: Code – Veronica,2000,mainline,5
4,re0,Resident Evil 0,2002,mainline,1
5,re4,Resident Evil 4,2005,mainline,6
6,re5,Resident Evil 5,2009,mainline,8
7,re_re,Resident Evil: Revelations,2012,spinoff,7
8,re6,Resident Evil 6,2012,mainline,10
9,re_re2,Resident Evil: Revelations 2,2015,spinoff,9
10,re7,Resident Evil 7: Biohazard,2017,mainline,11
11,re8,Resident Evil Village,2021,mainline,12
12,re_sr,Resident Evil Village – Shadow of Rose,2022,spinoff,13
13,re9,Resident Evil Requiem,2026,mainline,14

## Characters

this table contains the characters with their main role.

In [3]:
print(f"characters shape: {characters.shape}")
print(characters.head(20))

characters shape: (83, 3)
    id                 name     role
0    1   Leon Scott Kennedy     hero
1    2        Ashley Graham     hero
2    3             Ada Wong     hero
3    4      Ingrid Hunnigan     hero
4    5            Luis Sera     hero
5    6        Albert Wesker  villain
6    7                 HUNK     hero
7    8      Mercante d'armi     hero
8    9           Las Plagas  villain
9   10          Los Ganados  villain
10  11  Lord Osmund Saddler  villain
11  12        Ramon Salazar  villain
12  13       Bitores Mendez  villain
13  14         Jack Krauser  villain
14  15       Chris Redfield     hero
15  16       Jill Valentine     hero
16  17         Barry Burton     hero
17  18         Brad Vickers  support
18  19         Joseph Frost  support
19  20     Rebecca Chambers  support

## Game Appearance

this table contains the appearance of the characters in the games and their role in that specific game.

Contains the columns *"game_title"* and *"character_name"* for semplicity, should use the ids for the joins.

In [4]:
print(f"gameAppearance shape: {gameAppearance.shape}")
gameAppearance.head()

gameAppearance shape: (115, 5)

  game_id  character_id     role     game_title  character_name
0      re             6  villain  Resident Evil   Albert Wesker
1      re            15     hero  Resident Evil  Chris Redfield
2      re            16     hero  Resident Evil  Jill Valentine
3      re            17  support  Resident Evil    Barry Burton
4      re            18  support  Resident Evil    Brad Vickers

In [5]:
# for example we might wanna print the characters from Resident Evil 2
print(gameAppearance[gameAppearance["game_id"] == "re2"][["game_title","character_name"]])

         game_title      character_name
18  Resident Evil 2  Leon Scott Kennedy
19  Resident Evil 2            Ada Wong
20  Resident Evil 2     Claire Redfield
21  Resident Evil 2       Sherry Birkin
22  Resident Evil 2      William Birkin
23  Resident Evil 2      Annette Birkin
24  Resident Evil 2         Brian Irons
25  Resident Evil 2      Marvin Branagh
26  Resident Evil 2      Ben Bertolucci
27  Resident Evil 2        Robert Kendo

In [6]:
# or the games where Ada appeared
print(gameAppearance[gameAppearance["character_id"] == 3][["game_title","character_name"]])

         game_title character_name
19  Resident Evil 2       Ada Wong
38  Resident Evil 4       Ada Wong
59  Resident Evil 6       Ada Wong

## Scenes

this table contains the scenes of each game, with the title and the source where I scraped them from.

In [7]:
print(f"Scenes shape: {scenes.shape}")
scenes.head()

Scenes shape: (927, 4)

,game_id,scene_id,title,source
0,re,re_01,Opening FMV,https://gamefaqs.gamespot.com/ps/198462-reside...
1,re,re_02,Inside The Mansion,https://gamefaqs.gamespot.com/ps/198462-reside...
2,re,re_03,The Dining Room,https://gamefaqs.gamespot.com/ps/198462-reside...
3,re,re_04,Mysterious Puddle,https://gamefaqs.gamespot.com/ps/198462-reside...
4,re,re_05,Researcher's Will Event (Note: This scene will...,https://gamefaqs.gamespot.com/ps/198462-reside...

In [8]:
# We could print all the scenes from Resident Evil 2
scenes[scenes["game_id"] == "re2"]["title"]

36                        What have we got here?
37                 Hold you’re fire I’m a human.
38                 Survivors In the Other rooms.
39     Good too see your still among the living.
40                                      Ada Wong
                         ...
111              You’re So Gullible - Alternate.
112                                We're A Team.
113                                   Game Over.
114                   I have to find my brother.
115           Its up to us to take out umbrella!
Name: title, Length: 80, dtype: object

## Interactions

this table contains the characters appearing in each scene.

In [9]:
print(f"Interactions shape: {interactions.shape}")
interactions.head()

Interactions shape: (989, 3)

  game_id scene_id  character_id
0      re    re_01            16
1      re    re_01             6
2      re    re_01            15
3      re    re_02            16
4      re    re_02            17

In [10]:
# We could print all Ada's scenes in Resident Evil 2.
ada_scenes = (
    interactions[(interactions["character_id"] == 3) & (interactions["game_id"] == "re2")]
    .merge(
        scenes[["game_id", "scene_id", "title"]],
        on=["game_id", "scene_id"],
        how="left"
    )
    .sort_values(["game_id", "scene_id"])
)

print(ada_scenes[["game_id", "scene_id", "title"]])

   game_id scene_id                                title
0      re2   re2_05                             Ada Wong
1      re2   re2_06                Who the heck are you?
2      re2   re2_07                     It’s a dead end.
3      re2   re2_08              I’ll catch up with you.
4      re2   re2_09                       Get that Scum!
5      re2   re2_10                 Reckless and Stupid.
6      re2   re2_11               I have to talk to her.
7      re2   re2_12                  Eat this you freak.
8      re2   re2_13                    Alligator Attack.
9      re2   re2_14               The Sooner the better.
10     re2   re2_15                      Snap out of it.
11     re2   re2_16   We’re leaving this place together.
12     re2   re2_17                  You’re So Gullible.
13     re2   re2_18       Shut up, you’re gonna make it.
14     re2   re2_39                         Who are you?
15     re2   re2_64                             Ada Wong
16     re2   re2_65                Who the heck are you?
17     re2   re2_66         It’s a dead end - alternate.
18     re2   re2_67  I’ll catch up with you - Alternate.
19     re2   re2_68          Get that Scum! - Alternate.
20     re2   re2_69                 Reckless and Stupid.
21     re2   re2_70               I have to talk to her.
22     re2   re2_71              Where did you get that?
23     re2   re2_72               The Sooner the better.
24     re2   re2_73               We've finally arrived.
25     re2   re2_74                      Snap out of it.
26     re2   re2_75                        Welcome Back.
27     re2   re2_77                        We're A Team.
28     re2   re2_78                           Game Over.

In [11]:
# Or every scene where there's both Leon and Ada 
ada = interactions[interactions["character_id"] == 3][["game_id", "scene_id"]]
ada = ada.drop_duplicates()

leon = interactions[interactions["character_id"] == 1][["game_id", "scene_id"]]
leon = leon.drop_duplicates()

merged_scenes = (
    ada.merge(leon, on=["game_id", "scene_id"], how="inner")
    .merge(
        scenes[["game_id", "scene_id", "title"]],
        on=["game_id", "scene_id"],
        how="left"
    )
    .drop_duplicates()
    .sort_values(["game_id", "scene_id"])
)

print(merged_scenes[["game_id", "scene_id", "title"]])

   game_id scene_id                                title
0      re2   re2_05                             Ada Wong
1      re2   re2_06                Who the heck are you?
2      re2   re2_07                     It’s a dead end.
3      re2   re2_08              I’ll catch up with you.
4      re2   re2_09                       Get that Scum!
5      re2   re2_10                 Reckless and Stupid.
6      re2   re2_11               I have to talk to her.
7      re2   re2_13                    Alligator Attack.
8      re2   re2_14               The Sooner the better.
9      re2   re2_15                      Snap out of it.
10     re2   re2_16   We’re leaving this place together.
11     re2   re2_17                  You’re So Gullible.
12     re2   re2_18       Shut up, you’re gonna make it.
13     re2   re2_64                             Ada Wong
14     re2   re2_65                Who the heck are you?
15     re2   re2_66         It’s a dead end - alternate.
16     re2   re2_67  I’ll catch up with you - Alternate.
17     re2   re2_68          Get that Scum! - Alternate.
18     re2   re2_69                 Reckless and Stupid.
19     re2   re2_70               I have to talk to her.
20     re2   re2_71              Where did you get that?
21     re2   re2_72               The Sooner the better.
22     re2   re2_73               We've finally arrived.
23     re2   re2_74                      Snap out of it.
24     re2   re2_75                        Welcome Back.
25     re2   re2_77                        We're A Team.
26     re2   re2_78                           Game Over.
27     re4  re4_008                          Chapter 3-2
28     re4  re4_014                          Chapter 4-4
29     re4  re4_015                          Chapter 5-1
30     re4  re4_017                          Chapter 5-3
31     re4  re4_018                          Chapter 5-4
32     re6  re6_008                            Chapter 3
33     re6  re6_009                            Chapter 4